specVersion: 1.0.0
name: stable-asset-subql-v2
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: A basic Karura EVM example
repository: 'https://github.com/subquery/acala-evm-starter'
schema:
  file: ./schema.graphql
network:
  chainId: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  endpoint: 'wss://acala-polkadot.api.onfinality.io/public-ws	'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/AcalaEvm
    startBlock: 1310200
    processor:
      file: ./dist/acalaEvm.js
      options:
        abi: merkleDistributor
        address: '0x219FA396aE50f789b0cE5e27D6EcbE6b36ef49d9'
    assets:
      merkleDistributor:
        file: ./merkleDistributor.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleClaim
          kind: substrate/AcalaEvmEvent
          filter:
            topics:
              - 'Claimed(bytes32 indexed user,address userAddress,address indexed token,uint256 amount,uint256 indexed cycle,uint256 timestamp,uint256 blockNumber,address claimer)'
              - null
              - null
              - null